apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arena-replays
  namespace: arena
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arena-db
  namespace: arena
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arena-maps
  namespace: arena
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100Mi
